### PR TITLE
Fix printing the array of objects - Closes #474

### LINKED ISSUE #474: Handle arrays differently to objects when printing JSON
**Expected behavior:** 

Arrays should be displayed as arrays in JSON output.

**Actual behavior:** With JSON output we remove ANSI codes, but treat arrays like normal objects, so we get output like this:

```
{
	"0": {
		"rewards": "0",
		"vote": "10000000000000000",
		"producedBlocks": 0,
		"missedBlocks": 0,
		"username": "genesis_1",
		"rank": 63,
		"approval": 100,
		"productivity": 0,
		"account": {
			"address": "8273455169423958419L",
			"publicKey": "9d3058175acab969f41ad9b86f7a2926c74258670fe56b37c429c01fca9f2f0f",
			"secondPublicKey": ""
		}
	},
	"1": {
		"rewards": "0",
		"vote": "10000000000000000",
		"producedBlocks": 0,
		"missedBlocks": 0,
		"username": "genesis_23",
		"rank": 95,
		"approval": 100,
		"productivity": 0,
		"account": {
			"address": "263761216888896549L",
			"publicKey": "f33f93aa1f3ddcfd4e42d3206ddaab966f7f1b6672e5096d6da6adefd38edc67",
			"secondPublicKey": ""
		}
	}
}
```

### Versions

1.0.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
when removing ANSI, it was expecting object, but we were supplying an array.

### How did I fix it?
Check if the results are array or an object, and if an array go through removing ANSI process one by one.

### How to test it?
`lisky> list delegates genesis_1 genesis_5`
### Review checklist

* The PR solves #474 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/utils/print.js [hunk 1]
```diff
@@ -19,13 +19,18 @@ import config from './config';
...
+const removeANSIFromObject = result =>
 	Object.entries(result).reduce(
 		(strippedResult, [key, value]) =>
 			Object.assign({}, strippedResult, { [key]: stripANSI(value) }),
 		{},
 	);
 
+const removeANSI = result =>
+	Array.isArray(result)
+		? result.map(object => removeANSIFromObject(object))
```
Comment (willclarktech) [inline src/utils/print.js]: Prefer `result.map(removeANSIFromObject)`

File: src/utils/print.js [hunk 2]
```diff
@@ -19,13 +19,18 @@ import config from './config';
 import { shouldUseJSONOutput, shouldUsePrettyOutput } from './helpers';
 import tablify from './tablify';
 
-const removeANSI = result =>
+const removeANSIFromObject = result =>
```
Comment (willclarktech) [inline src/utils/print.js]: Maybe we should rename `result` to `object` in line with the below change?
