### PR TITLE
Validate config on load - Closes #493

### LINKED ISSUE #493: Migration of the config file 0.3 -> 1.0
### Description

During the update from version 0.3 to the current 1.0-beta the old config in `~/.lisky/config.json` stays the same. Due to differences in the required properties ie. rename `liskJS` to `api`, the behavior of the application can be very confusing for a potential user.

### Steps to Reproduce

1. `npm i -g lisky@0.3`
1. start `lisky`, the config file is created
1. `npm i -g lisky@beta`
1. start `lisky` again
1. type `config`

**Expected behavior:**

```
{
	"name": "lisky",
	"json": false,
	"api": {
		"node": "http://localhost:4000",
		"network": "test"
	},
	"pretty": false
}
```

**Actual behavior:**

Invalid config file is provided to the 1.0 instance:

```
{
	"name": "lisky",
	"json": false,
	"liskJS": {
		"node": "localhost",
		"port": "4000",
                ...
	},
	"pretty": false
}
```

**Reproduces how often:**
always

### Versions

1.0.0-beta.1

### PR DESCRIPTION
**Pull request by willclarktech**
### What was the problem?

Config files with missing keys would not prevent Lisk Commander from starting, and a crash could occur when using the `set` command later on.

### How did I fix it?

I added validation when the config is loaded.

### How to test it?

Start Lisk Commander with corrupted config files (or config files generated by pre 1.0.0 versions) and try `set`.

### Review checklist

* The PR solves #493 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/utils/config.js [hunk 1]
```diff
@@ -57,24 +59,30 @@ const attemptToCreateFile = path => {
...
+
+const attemptToValidateConfig = (config, path) => {
+	const rootKeys = CONFIG_VARIABLES.map(key => key.split('.')[0]);
+	const fn = () =>
+		rootKeys.forEach(key => {
+			if (!Object.keys(config).includes(key)) {
+				throw new ValidationError(`Key ${key} not found in config file.`);
+			}
+		});
+	const errorCode = 3;
```
Comment (shuse2) [inline src/utils/config.js]: what are these errorCode based on? maybe it's better to define it, or follow standards?

File: test/steps/files/1_given.js [hunk 2]
```diff
@@ -177,7 +177,18 @@ export function theFileIsNotValidJSON() {
 	fsUtils.readJSONSync.throws('Invalid JSON');
 }
 
-export function theFileIsValidJSON() {
+export function theFileIsMissingRequiredKeys() {
+	const userConfig = {
+		name: 'custom-name',
```
Comment (shuse2) [inline test/steps/files/1_given.js]: maybe check the nested values too?

File: src/utils/config.js (hunk 1 above)
Comment (willclarktech) [reply src/utils/config.js]: It was just incrementing from 1 every time a new error type was needed in this file. I'm very up for following an existing standard, but the natural choice seems to be https://nodejs.org/api/errors.html#errors_node_js_error_codes, but it's unclear if they have codes for all our situations. Do you know of a good alternative?

Comment (shuse2) [reply src/utils/config.js]: I think the node error code is good although im not sure if it represents number tho.
Maybe something like
[https://shapeshed.com/unix-exit-codes/](https://shapeshed.com/unix-exit-codes/)
Even if we don't follow the standard, we should probably have some meaning behind the number.

File: test/steps/files/1_given.js (hunk 2 above)
Comment (shuse2) [reply test/steps/files/1_given.js]: ah thats true, as long as the key exists, it should be able to set.
I think it's good then

**Comment by shuse2** [comment]
cover all ='(
