### PR TITLE
Fix recursive to have limit and catch failed API - Closes #452

### LINKED ISSUE #452: Investigate maximum call stack exceeded problem
### Description

Running Lisky v0.3.0 against a node running Core v1.0.0 can result in the following:

```
lisky> list delegates tosch
╔═════════╤═════════════════════════════════════════════════════════╗
║ success │ message                                                 ║
╟─────────┼─────────────────────────────────────────────────────────╢
║ false   │ could not create http request to any of the given peers ║
╚═════════╧═════════════════════════════════════════════════════════╝
lisky> get block 2606559219099047919
RangeError: Maximum call stack size exceeded
    at getKeys (~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:73:31)
    at ~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:79:72
    at Array.map (native)
    at getKeys (~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:74:30)
    at~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:79:72
    at Array.map (native)
    at getKeys (~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:74:30)
    at ~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:79:72
    at Array.map (native)
    at getKeys (~/.nvm/versions/node/v6.11.5/lib/node_modules/lisky/dist/utils/tablify.js:74:30)
```

**Expected behavior:** Unintended uses like the above should be handled cleanly.

**Actual behavior:** There's a maximum call stack size exceeded error.

### PR DESCRIPTION
**Pull request by shuse2**
Closes #452 

Ported from #457 

### What was the problem?
- Deeply nested response object
- Recursive without limit exceeds the limit of call stack

### How did I fix it?
- Add limit to recursive feature
- Handle failed API call

### How to test it?
Run `get block 2606559219099047919` or any `get` command without running lisk-core

### Review checklist
* The PR solves #452

### CODE REVIEW

File: test/specs/utils/query.js [hunk 1]
```diff
@@ -41,6 +41,26 @@ describe('Query class', () => {
 				then.theQueryInstanceShouldHaveAHandlerFor,
 			);
 			describe('#sendRequest', () => {
+				When(
+					'the query instance sends a request and the lisk API instance returns the success response',
```
Comment (willclarktech) [inline test/specs/utils/query.js]: `resolves with a successful response` (and corresponding change to the function name).

File: test/specs/utils/query.js [hunk 2]
```diff
@@ -41,6 +41,26 @@ describe('Query class', () => {
...
+					when.theQueryInstanceSendsARequestAndTheLiskAPIInstanceReturnsTheSuccessResponse,
+					() => {
+						Then(
+							'it should resolve to the result of sending the request',
+							then.itShouldResolveToTheResultOfSendingTheRequest,
+						);
+					},
+				);
+				When(
+					'the query instance sends a request and the lisk API instance returns the fail response',
```
Comment (willclarktech) [inline test/specs/utils/query.js]: `resolves with a failed response` (and corresponding change to the function name).

File: test/specs/utils/tablify.js [hunk 3]
```diff
@@ -66,6 +66,18 @@ describe('tablify util', () => {
...
 		});
 	});
+	Given('a cyclic object', given.aCyclicObject, () => {
+		When('the object is tablified', when.theObjectIsTablified, () => {
+			Then(
+				'the returned table should have a head with the cyclic object’s keys',
+				then.theReturnedTableShouldHaveAHeadWithTheCyclicObjectKeys,
+			);
+			Then(
+				'the returned table should have a row with the cyclic object’s values including an error for the cyclic value',
```
Comment (willclarktech) [inline test/specs/utils/tablify.js]: `including a message for the cycle value` (and corresponding change for the function name).

File: test/steps/api/1_given.js [hunk 4]
```diff
@@ -16,5 +16,11 @@
 import liskAPIInstance from '../../../src/utils/api';
 
 export function aLiskAPIInstance() {
+	const sendRequestDefaultResult = { success: true };
+	sandbox
+		.stub(liskAPIInstance, 'sendRequest')
+		.resolves(sendRequestDefaultResult);
+	sandbox.stub(liskAPIInstance, 'setTestnet');
```
Comment (willclarktech) [inline test/steps/api/1_given.js]: Stubbing should be done in a setup step.

File: test/steps/queries/2_when.js [hunk 5]
```diff
@@ -15,6 +15,29 @@
...
 import { processQueryResult } from '../../../src/utils/helpers';
 
+export function theQueryInstanceSendsARequestAndTheLiskAPIInstanceReturnsTheSuccessResponse() {
+	const { liskAPIInstance, queryInstance } = this.test.ctx;
+	const sendRequestResult = { success: true };
+	liskAPIInstance.sendRequest.resolves(sendRequestResult);
+	this.test.ctx.sendRequestResult = sendRequestResult;
+	const returnValue = queryInstance.sendRequest('', {});
+	this.test.ctx.returnValue = returnValue;
+	return returnValue.catch(e => e);
```
Comment (willclarktech) [inline test/steps/queries/2_when.js]: Some blank lines would be helpful to separate the stages of this step (and the one below).

File: test/steps/setup.js [hunk 6]
```diff
@@ -186,6 +192,9 @@ const restoreEnvVariable = variable =>
 			delete process.env[variable];
 		}
 	};
+export function setUpLiskJSAPIInstance() {
```
Comment (willclarktech) [inline test/steps/setup.js]: The exported functions should be named specifically for the suite. I.e. `setUpUtilQuery`. And we could do with a blank line before this function.

File: test/steps/setup.js [hunk 7]
```diff
@@ -79,15 +79,21 @@ const setUpReadlineStubs = () => {
 };
 
 function setUpLiskJSAPIStubs() {
+	const sendRequestDefaultResult = { success: true };
```
Comment (willclarktech) [inline test/steps/setup.js]: Is this needed here or will we always define it later?

File: test/steps/setup.js (hunk 6 above)
Comment (shuse2) [reply test/steps/setup.js]: for testing `Query Class` suite, it would be like `setUpQueryClass`?

File: test/steps/setup.js (hunk 7 above)
Comment (shuse2) [reply test/steps/setup.js]: it's the default result, if we don't need to change it, we can use as it is.

File: test/steps/setup.js (hunk 6 above)
Comment (willclarktech) [reply test/steps/setup.js]: We use `setUpUtilCrypto` even though that's a class. I would say class is an implementation detail, and the name should be about the module.

File: test/specs/utils/tablify.js [hunk 8]
```diff
@@ -57,12 +57,16 @@ describe('tablify util', () => {
 	Given('a deeply nested object', given.aDeeplyNestedObject, () => {
 		When('the object is tablified', when.theObjectIsTablified, () => {
 			Then(
-				'the returned table should have a head with the object’s deeply nested keys',
-				then.theReturnedTableShouldHaveAHeadWithTheObjectDeeplyNestedKeys,
+				'it should throw a print error "Maximum nesting of the object is exceeded to be displayed as a table."',
```
Comment (willclarktech) [inline test/specs/utils/tablify.js]: `it should throw print error` to match function name.

File: test/specs/utils/tablify.js [hunk 9]
```diff
@@ -57,12 +57,16 @@ describe('tablify util', () => {
...
+				then.itShouldThrowPrintError,
 			);
+		});
+	});
+	Given('a cyclic object', given.aCyclicObject, () => {
+		When('the object is tablified', when.theObjectIsTablified, () => {
 			Then(
-				'the returned table should have a row with the object’s deeply nested values',
-				then.theReturnedTableShouldHaveAHeadWithTheObjectDeeplyNestedValues,
+				'it should throw a print error "Maximum nesting of the object is exceeded to be displayed as a table."',
```
Comment (willclarktech) [inline test/specs/utils/tablify.js]: As above.

File: src/utils/tablify.js [hunk 10]
```diff
@@ -54,12 +55,17 @@ const reduceKeys = (keys, row) => {
 	return keys.concat(newKeys);
 };
 
-const getKeys = data =>
-	Object.entries(data)
+const getKeys = (data, limit = 3, loop = 1) => {
+	if (loop > limit) {
+		throw new PrintError(
+			'Maximum nesting of the object is exceeded to be displayed as a table.',
```
Comment (willclarktech) [inline src/utils/tablify.js]: `Output cannot be displayed in table format: Maximum object depth of 3 was exceeded. Consider using JSON output format.`

File: src/utils/tablify.js [hunk 11]
```diff
@@ -54,12 +55,17 @@ const reduceKeys = (keys, row) => {
 	return keys.concat(newKeys);
 };
 
-const getKeys = data =>
-	Object.entries(data)
+const getKeys = (data, limit = 3, loop = 1) => {
+	if (loop > limit) {
+		throw new PrintError(
```
Comment (willclarktech) [inline src/utils/tablify.js]: This will crash Lisk Commander rather than printing the message in table format. Is that what we want?

File: test/specs/utils/error.js [hunk 12]
```diff
@@ -66,4 +66,24 @@ describe('Custom Errors', () => {
...
+					'it should print the error message in red',
+					then.itShouldPrintTheErrorMessageInRed,
+				);
+				Then(
+					'the error should have the name "PrintError"',
+					then.theErrorShouldHaveTheName,
+				);
+				Then(
+					'the error should be an instance of Node’s built-in Error',
+					then.theErrorShouldBeInstanceOfNodesBuiltInError,
```
Comment (willclarktech) [inline test/specs/utils/error.js]: I realise this was here before, but can you update the name of this function to match the descriptions?

File: src/utils/tablify.js (hunk 11 above)
Comment (shuse2) [reply src/utils/tablify.js]: It doesn't show in table format, but it doesn't crash the commander neither.
I think it's more consistent with other types of `Error`

File: test/specs/utils/tablify.js (hunk 8 above)
Comment (shuse2) [reply test/specs/utils/tablify.js]: it was actually like that and I changed it last minutes ='(
