### PR TITLE
:bug: Fix tablify deeper objects bug - Closes #319

### LINKED ISSUE #319: getKeys function in tablify does not correctly handle nested objects
Tests should be added and this check should be corrected:

https://github.com/LiskHQ/lisky/blob/1c3dde3f52df060fd64880768a1c01f3c4b93233/src/utils/tablify.js#L36

### PR DESCRIPTION
**Pull request by Tosch110**
Closes #319

### CODE REVIEW

File: test/specs/utils/tablify.js [hunk 1]
```diff
@@ -42,6 +42,14 @@ describe('tablify util', () => {
 			it('Then the returned table should have a row with the object’s nested values', then.theReturnedTableShouldHaveAHeadWithTheObjectNestedValues);
 		});
 	});
+	describe('Given a deeper nested object', () => {
+		beforeEach(given.aDeeperNestedObject);
+		describe('When the object is tablified', () => {
+			beforeEach(when.theObjectIsTablified);
+			it('Then the returned table should have a head with the object’s nested keys', then.theReturnedTableShouldHaveAHeadWithTheObjectDeepNestedKeys);
+			it('Then the returned table should have a row with the object’s nested values', then.theReturnedTableShouldHaveAHeadWithTheObjectDeepNestedValues);
```
Comment (willclarktech) [inline test/specs/utils/tablify.js]: Descriptions diverge from function names. Should be `Then the returned table should have a head with the object’s deeply nested keys/values`.

File: test/specs/utils/tablify.js [hunk 2]
```diff
@@ -42,6 +42,14 @@ describe('tablify util', () => {
 			it('Then the returned table should have a row with the object’s nested values', then.theReturnedTableShouldHaveAHeadWithTheObjectNestedValues);
 		});
 	});
+	describe('Given a deeper nested object', () => {
```
Comment (willclarktech) [inline test/specs/utils/tablify.js]: `Given a deeply nested object` (and corresponding function name)
